/**
 * This file was generated by @pikku/cli@0.12.15
 */
/**
 * Auto-generated public RPC HTTP endpoint
 * Do not edit manually - regenerate with 'npx pikku'
 */
import { pikkuSessionlessFunc, defineHTTPRoutes, wireHTTPRoutes } from '../pikku-gen/pikku-types.gen.js'

export const rpcCaller = pikkuSessionlessFunc<
  { rpcName: string; data?: unknown },
  unknown
>({
  auth: false,
  func: async (_services, { rpcName, data }, { rpc }) => {
    return await rpc.exposed(rpcName, data)
  },
})

export const workflowCaller = pikkuSessionlessFunc<
  { workflowName: string; input?: unknown },
  { runId: string }
>({
  auth: false,
  func: async (_services, { workflowName, input }, { rpc }) => {
    return await (rpc.startWorkflow as Function)(workflowName, input || {})
  },
})

export const rpcRoutes = defineHTTPRoutes({
  auth: false,
  tags: ['pikku:public'],
  routes: {
    rpc: {
      route: '/rpc/:rpcName',
      method: 'post',
      func: rpcCaller,
    },
    workflow: {
      route: '/rpc/workflow/:workflowName',
      method: 'post',
      func: workflowCaller,
    },
  },
})

wireHTTPRoutes({ routes: { rpc: rpcRoutes } })
